name: pull request workflow

on:
  pull_request:
    branches: ['**']

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pull_request_workflow:
    runs-on: ubuntu-latest
    name: pull request workflow

    steps:
      - name: checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: setup bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: install dependencies
        run: make install-frozen

      - name: run checks
        run: make check-ci

      - name: run tests
        run: make test

      - name: build
        run: make build
